version: '3'

services:
  base: &base
    # image: ghcr.io/ismoillmirabbosoff/chatwoot:main
    build: .
    environment:
      SECRET_KEY_BASE: replace_with_lengthy_secure_hex
      FRONTEND_URL: http://0.0.0.0:3000
      ASSET_CDN_HOST: ""
      FORCE_SSL: "false"
      ENABLE_ACCOUNT_SIGNUP: "false"
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: ""
      REDIS_SENTINELS: ""
      REDIS_SENTINEL_MASTER_NAME: ""
      POSTGRES_DATABASE: chatwoot
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      MAILER_SENDER_EMAIL: Chatwoot <accounts@chatwoot.com>
      SMTP_DOMAIN: chatwoot.com
      SMTP_ADDRESS: ""
      SMTP_PORT: 1025
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_AUTHENTICATION: ""
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: peer
      MAILER_INBOUND_EMAIL_DOMAIN: ""
      RAILS_INBOUND_EMAIL_SERVICE: ""
      RAILS_INBOUND_EMAIL_PASSWORD: ""
      MAILGUN_INGRESS_SIGNING_KEY: ""
      MANDRILL_INGRESS_API_KEY: ""
      ACTIVE_STORAGE_SERVICE: local
      S3_BUCKET_NAME: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_REGION: ""
      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: info
      LOG_SIZE: 500
      FB_VERIFY_TOKEN: ""
      FB_APP_SECRET: ""
      FB_APP_ID: ""
      IG_VERIFY_TOKEN: ""
      TWITTER_APP_ID: ""
      TWITTER_CONSUMER_KEY: ""
      TWITTER_CONSUMER_SECRET: ""
      TWITTER_ENVIRONMENT: ""
      SLACK_CLIENT_ID: ""
      SLACK_CLIENT_SECRET: ""
      GOOGLE_OAUTH_CLIENT_ID: ""
      GOOGLE_OAUTH_CLIENT_SECRET: ""
      GOOGLE_OAUTH_CALLBACK_URL: ""
      IOS_APP_ID: L7YLMN4634.com.chatwoot.app
      ANDROID_BUNDLE_ID: com.chatwoot.app
      ANDROID_SHA256_CERT_FINGERPRINT: AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8
      ENABLE_PUSH_RELAY_SERVER: "true"
      STRIPE_SECRET_KEY: ""
      STRIPE_WEBHOOK_SECRET: ""
      DIRECT_UPLOADS_ENABLED: ""
      AZURE_APP_ID: ""
      AZURE_APP_SECRET: ""
    volumes:
      - /data/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: postgres:15
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    environment:
      REDIS_PASSWORD: ""
    volumes:
      - /data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
